-- 코드를 입력하세요
SELECT b.USER_ID, b.NICKNAME, CONCAT(CITY, " ", STREET_ADDRESS1, " ", STREET_ADDRESS2) AS "전체주소",
    CONCAT(SUBSTR(TLNO, 1, 3), "-", SUBSTR(TLNO, 4, 4), "-", SUBSTR(TLNO, 8, 4)) AS "전화번호"
FROM USED_GOODS_BOARD a JOIN USED_GOODS_USER b ON a.WRITER_ID = b.USER_ID
GROUP BY a.WRITER_ID
HAVING COUNT(*) >= 3
ORDER BY 1 DESC