-- 코드를 입력하세요
SELECT CAR_ID, 
    CASE WHEN 
        SUM(CASE WHEN DATE_FORMAT("2022-10-16", '%Y-%m-%d') BETWEEN START_DATE AND END_DATE
            THEN 1 ELSE 0 END) = 0 
        THEN "대여 가능" 
        ELSE "대여중" 
    END
AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY 1
ORDER BY 1 DESC